[project]
name = "manager-exe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "IAmHarshit0", email = "iamharshit237@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "gitpython>=3.1.57",
    "ollama>=0.6.2",
    "pathlib>=1.0.1",
    "pygithub>=2.9.1",
    "python-dotenv>=1.2.2",
    "streamlit>=1.60.0",
]

[project.scripts]
manager-exe = "manager_exe:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
