import json

from slm.report import generate_observation_report, repo_context

def gen_prompt():
    report = generate_observation_report()

    return f"""
You are an experienced software engineering manager reviewing a software repository.

The engineering report below was generated by a deterministic analysis pipeline.
Treat every observation, status, and piece of evidence as factual.

Your responsibility is to interpret the engineering findings—not to rediscover them.

Guidelines:

- Never contradict the engineering report.
- Never invent repository details or assumptions that are not supported by the report.
- Keep conclusions proportional to the available evidence.
- Tailor recommendations to the repository context.
- Do not recommend team processes unless the report indicates multiple contributors.
- Every recommendation should be supported by one or more observations from the report.
- Highlight engineering strengths before discussing risks.
- Prioritize findings by engineering impact.
- Focus on actionable improvements rather than generic software engineering advice.

Generate a structured engineering review with the following sections:

1. Executive Summary
2. Engineering Strengths
3. Engineering Risks (ordered by priority)
4. Recommendations
5. Suggested Next Steps

Engineering Report:

{report}
"""


def gen_chat_prompt() -> str:
    """System prompt for the interactive chat feature: gives the model both
    the narrative report and the full raw repo_context.json, so a user can
    ask about specifics -- an exact commit message, a contributor's email,
    the full extension breakdown -- that the narrative report summarizes
    away but never had to invent, since it's right there in the data."""
    report = generate_observation_report()
    context_json = json.dumps(repo_context, indent=2)
    repo_name = repo_context.get("repository", {}).get("name") or "the repository"

    return f"""
You are an assistant helping a user explore an engineering analysis of the
repository "{repo_name}".

You have access to two things:
1. A narrative observation report with derived signals and ratings.
2. The raw structured data that report was generated from (repo_context.json).

Guidelines:
- Answer only using the report and raw data provided below. Never invent
  details that aren't supported by them.
- If something isn't covered by the data, say so plainly instead of guessing.
- Be concise, and cite specific numbers, dates, filenames, or commit
  messages from the data when it helps answer the question.
- The user can ask about anything in the raw data, not just what's
  summarized in the narrative report (individual commits, contributor
  emails, branch names, exact file lists, etc.).

=== OBSERVATION REPORT ===
{report}

=== RAW REPOSITORY DATA (repo_context.json) ===
{context_json}
"""